engines:
  duplication:
    enabled: true
    config:
      languages:
        - php
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
  phan:
    enabled: true
    config:
      backward-compatibility-checks: true
      dead-code-detection: true
      file_extensions: "php"
exclude_paths:
  - tests/
  - build/
  - vendor/
ratings:
  paths:
    - "**.php"