language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm
after_script:
  - vendor/bin/test-reporter
addons:
    code_climate:
    
        coverage_report: tests/logs/clover.xml
install:
- composer install