language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm
after_script:
  - vendor/bin/test-reporter --coverage-report build/logs/clover.xml
addons:
    code_climate:
    
install:
  - composer install